Mutagen optimization
scandipwa/scandipwa-base pull request #63
Opened 2020-02-19 14:04 UTC by negzu

Bring the project up using Mutagen.
TODO: in closest time make docker-compose files to be able to bring the project up without Mutagen.

2020-02-21 14:21 UTC, yeegor commented
For now I am unable to install backend module using this setup. Investigating.

2020-02-24 04:37 UTC, alfredsgenkins requested changes

2020-02-24 04:37 UTC, alfredsgenkins commented on build/php/Dockerfile
> +    iputils-ping \
I think this is not used anymore.

2020-02-24 04:37 UTC, alfredsgenkins commented on deploy/shared/conf/local-ssl/ca.conf
> +default_days = 825
Please add comments why we did this

2020-02-24 04:37 UTC, alfredsgenkins commented on deploy/start-demo.sh
> +  if ping -c 1 frontend &> /dev/null
We still have this? I thought we removed it!

2020-02-24 04:37 UTC, alfredsgenkins commented on deploy/start-demo.sh
> +  if ping -c 1 frontend &> /dev/null
Because we have additional .sh file for Frontend.

2020-02-24 04:37 UTC, alfredsgenkins commented on deploy/start.sh
> +### Customdc commands for assets compilation
Typo?

2020-02-24 04:40 UTC, alfredsgenkins commented
Please try adding `container_name: my-web-container` for all setvices docker-compose.mutagen.yml or in docker-compose.local.yml to resolve naming issue. Note: this prevents from scaling.

2020-02-24 04:41 UTC, alfredsgenkins commented
Please link a doc for this, otherwise Ilja won't review this.

2020-02-24 04:58 UTC, alfredsgenkins commented
Try specifying user in docker-compose like this: https://docs.docker.com/compose/compose-file/#userns_mode#domainname-hostname-ipc-mac_address-privileged-read_only-shm_size-stdin_open-tty-user-working_dir

2020-02-24 11:50 UTC, yeegor commented on deploy/shared/conf/local-ssl/ca.conf
> +default_days = 825
I did that to fix certificate issue on Mac, which did no help. Reverting.

2020-02-24 12:03 UTC, eli-l requested changes

2020-02-24 12:03 UTC, eli-l commented on build/frontend/start.sh
> +cd app/design/frontend/Scandiweb/pwa/
You've changed the mountpoint / workdir, why?

2020-02-24 12:03 UTC, eli-l commented on deploy/start-demo.sh
> +  if ping -c 1 frontend &> /dev/null
Demo has nothing common with frontend container, why there are changes here?

2020-02-24 12:03 UTC, eli-l commented on deploy/start-with-frontend.sh
> +#!/usr/bin/env bash
Should I use this shell script to start the stack with frontend container or...? File name is completely unclear here.

2020-02-24 12:03 UTC, eli-l commented on deploy/start.sh
> +  echo "${blue}${bold}Building PWA theme${normal}"
Why the check was removed?

2020-02-24 12:03 UTC, eli-l commented on docker-compose.yml
> +      - nginx-data:/var/www/public/pub
What's the reason of introducing new volume? Is that mutagen limitation?

2020-02-24 12:10 UTC, yeegor commented on docker-compose.yml
> +      - nginx-data:/var/www/public/pub
It is not mutagen-related, but apparently it is faster to sync many small named volumes with their containers than one huge app-data volume with many containers.

2020-02-24 12:12 UTC, yeegor commented on deploy/start-with-frontend.sh
> +#!/usr/bin/env bash
Yes, you should use this shell script to start the stack with frontend container. That is why it is called "start-with-frontend". I am open to your proposals regarding the naming of this file.

2020-02-24 12:13 UTC, yeegor commented on deploy/start.sh
> +  echo "${blue}${bold}Building PWA theme${normal}"
Because now there are two start scripts: 'start' which builds the theme inside of app container and 'start with frontend' which builds the theme in the frontend container. The deploy is twice as fast with this configuration because theme is able to be compiled asynchronously in frontend container while app is getting up if it is needed.

2020-02-24 12:14 UTC, yeegor commented on build/frontend/start.sh
> +cd app/design/frontend/Scandiweb/pwa/
It is done in order not to sync huge app-data volume with frontend container, who needs like 2% of the information contained in it, it speeds the process up.

2020-02-24 12:40 UTC, yeegor commented on docker-compose.yml
> +      - nginx-data:/var/www/public/pub
It is not the only volume introduced, see core-frontend-data.
I also wanted to create a frontend-data volume to mount it into the frontend container, but the issues occur because we then would need to mount vendor and app/design/frontend/scandiweb/pwa folders separately and vendor doesn't want to be mounted separately for some reason :(

2020-02-24 12:41 UTC, yeegor commented on build/php/Dockerfile
> +    iputils-ping \
Removed.

2020-02-24 12:44 UTC, yeegor commented
Known issue: Currently I am experiencing problems with configuring Xdebug on my Mac using this configuration. 
Investigating.

2020-02-24 13:33 UTC, yeegor commented
> Try specifying user in docker-compose like this: https://docs.docker.com/compose/compose-file/#userns_mode#domainname-hostname-ipc-mac_address-privileged-read_only-shm_size-stdin_open-tty-user-working_dir

When I refer to user 'user' by name, the container does not start.
When I refer to user 'user' by UID 1000, I get the following error:
`mutagen-powered-app | Starting with UID : 0
mutagen-powered-app | useradd: Permission denied.
mutagen-powered-app | useradd: cannot lock /etc/passwd; try again later.
mutagen-powered-app | error: failed switching to "user": unable to find user user: no matching entries in passwd file`

2020-02-24 14:35 UTC, eli-l commented on build/frontend/start.sh
> +cd app/design/frontend/Scandiweb/pwa/
What is "like 2%"?

2020-02-24 14:38 UTC, eli-l commented on deploy/start.sh
> +  echo "${blue}${bold}Building PWA theme${normal}"
I don't care about the speed if functionality is broken. Instead of not building if setup:upgrade returned non-zero code - you built a script that does not care abt Magento status.
start.sh is a default entrypoint, why do you make some changes there refering frontend container etc. FE containers got own files.

2020-02-24 14:39 UTC, eli-l commented on docker-compose.yml
> +      - nginx-data:/var/www/public/pub
> It is not mutagen-related, but apparently it is faster to sync many small named volumes with their containers than one huge app-data volume with many containers.

Ok, means that you prefer "faster sync" to developer, who is adding additional file and want it to be served directly from nginx, to spend TONS of time to find out it is not mounted to nginx? This approach is wrong.

2020-02-24 15:47 UTC, eli-l requested changes

2020-02-24 15:47 UTC, eli-l commented on build/frontend/Dockerfile
Why these scripts were removed? These files contains deployment logic, not application version/dependencies.

2020-02-24 15:47 UTC, eli-l commented on build/frontend/start-core.sh
> +echo "Waiting for initial files to be synced"
I'd be more up to enforce re-building when dependencies are changed, rather than to use such a hacky solution. It is needed not because Docker is not-to-good, but because we are moving away from it's best practices to far.

2020-02-24 15:47 UTC, eli-l commented on build/frontend/start.sh
> +cd app/design/frontend/Scandiweb/pwa/
Seems I won't get an expected answer, but it is up to nginx config file to control what is served and what is not, you must not decide on which files to copy/sync and which not, as this will lead to misbehavior.
First of all - it is not up to sync mechanism to decide which files are available to nginx and which to fpm.
Second - this will lead to different behavior with mutagen and without it. It is not the way this should be implemented. Make the behavior consistent!

2020-02-24 15:47 UTC, eli-l commented on build/frontend/start.sh
>  #!/bin/bash
Since you've been touching start.sh and start-core.sh - this is the place we could use some "optimization" and remove the "core" file, utilizing environment variables and docker-compose instead, as all "core" configs are meant for core developers only, and we could share the knowledge quickly.
The "unification" could be done with envvar, that would indicate which config file to use. This would be good improvement.

2020-02-24 15:47 UTC, eli-l commented on build/rendertron/Dockerfile
> -FROM node:10-slim
Why base image has been changed? How it is related to mutagen?

2020-02-24 15:47 UTC, eli-l commented on deploy/start-demo.sh
> +
As already mentioned - why this check has been removed? There is not sense to build a theme if Migration failed. Why you're changing the deployment logic?

2020-02-24 15:47 UTC, eli-l commented on deploy/start-demo.sh
> +echo "${blue}${bold}Waiting for Mutagen to sync initial filese${normal}"
Composer.json/lock is always in a container, as these are added during the build.
Does mutagen add additional layer that is empty on top of containers FS, similar to local mount? Even so - this behavior is related only to local.

2020-02-24 16:30 UTC, eli-l requested changes
Global comment:
- pay attention and rework workdirs, don't rework/redefine them unless absolutely necessary for Mutagen (never?)
- source code must be shared between nginx and app containers, no matter how you run it (no mounting, docker native, mutagen), it is done for a reason.
- revisit all the changes (all existing files that have been edited by you), and unless this is absolutely good for ALL environments and use cases - move these changes to a separate file (even it is 300 lines long).
- remove changes to the existing services, that are not related to your task

2020-02-24 16:30 UTC, eli-l commented on deploy/start-demo.sh
> +echo "${blue}${bold}Waiting for Mutagen to sync initial filese${normal}"
For mutagen - use another start scripts, hopefully we'll unify it one day.

2020-02-24 16:30 UTC, eli-l commented on deploy/start-with-frontend.sh
> +#!/usr/bin/env bash
"start-when-frontend-serving.sh" - would clearly provide use case of this file, isn't it?

2020-02-24 16:30 UTC, eli-l commented on deploy/start.sh
> +  echo "${blue}${bold}Building PWA theme${normal}"
Get check back, this is the default file used in most of environments.

2020-02-24 16:30 UTC, eli-l commented on deploy/start.sh
> +echo "${blue}${bold}Waiting for Mutagen to sync initial filese${normal}"
This is the default file - nothing related to local, mutagen or other side-cases must be added here.
create deploy/mutagen directory, put there everything related to Mutagen sync, anyway you have mutagen dedicated docker-compose files, controlling start script is extremely easy there.

2020-02-24 16:30 UTC, eli-l commented on docker-compose.core.yml
> +      - ./build/frontend/start-core.sh:/start-core.sh
Build file into container, do not mount it from the host.

2020-02-27 16:39 UTC, yeegor commented on deploy/start-demo.sh
> +  if ping -c 1 frontend &> /dev/null
returned it back.

2020-02-27 16:40 UTC, yeegor commented on deploy/start-demo.sh
> +
I have returned this check into start-demo script. Script that starts with frontend container has no need in this check because theme is being built asynchronously, independent of app container.

2020-02-27 16:41 UTC, yeegor commented on build/frontend/start.sh
> +cd app/design/frontend/Scandiweb/pwa/
Returned mounting all the app-data volume into the frontend container.

2020-02-27 16:43 UTC, yeegor commented on build/rendertron/Dockerfile
> -FROM node:10-slim
It is changed in the 2.x-stable as well to resolve issues with wget not being available inside the container. See the following commit: https://github.com/scandipwa/scandipwa-base/commit/f672efcafeb431dcfd75cec25e1e773e8d4c16ef

2020-02-27 16:46 UTC, yeegor commented on deploy/start-with-frontend.sh
> +#!/usr/bin/env bash
It does as well, renamed.

2020-02-27 16:48 UTC, yeegor commented on deploy/start.sh
> +  echo "${blue}${bold}Building PWA theme${normal}"
Returned the check.

2020-02-27 16:54 UTC, yeegor commented on docker-compose.yml
> +      - nginx-data:/var/www/public/pub
Current solution considers mounting app-data into nginx container. This way we will not have one more docker-compose file. Is there any difference in mounting app-data volume into nginx or creating a bind mount? Additional sync sessions will be slower than direct named volume mount, should I create them between nginx and local fs instead of mounting app-data volume into nginx?

2020-02-27 17:13 UTC, yeegor commented on build/frontend/start-core.sh
> +echo "Waiting for initial files to be synced"
Do you propose to do install dependencies during the frontend container build and remove `npm ci` from this script at all, leaving it with a single purpose of launching pm2-runtime? Then we can get rid of these deployment scripts of frontend container and do that with docker-compose file `command: ['npm', 'run', 'pm2-watch']` directive?

2020-02-28 09:19 UTC, yeegor commented on build/frontend/Dockerfile
Returned a single script to build frontend container

2020-02-28 09:20 UTC, yeegor commented on build/frontend/start-core.sh
> +echo "Waiting for initial files to be synced"
`npm ci` was moved to frontend container build script.

2020-02-28 09:21 UTC, yeegor commented on build/frontend/start.sh
>  #!/bin/bash
Implemented.

2020-04-21 16:30 UTC, merged